<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPdqpcyn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPdqpcyn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPdqpcyn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPdqpcyn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPdqpcyn\appProdProjectContainer([
    'container.build_hash' => 'Pdqpcyn',
    'container.build_id' => '00361f81',
    'container.build_time' => 1631449162,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPdqpcyn');
