<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCfhqvbc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCfhqvbc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCfhqvbc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCfhqvbc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCfhqvbc\appDevDebugProjectContainer([
    'container.build_hash' => 'Cfhqvbc',
    'container.build_id' => 'e49af8a1',
    'container.build_time' => 1635888579,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCfhqvbc');
